/**
 * Bundles the pure daily-plan pipeline (src/services/dailyPlan.js + its imports)
 * into a CommonJS file the API can require, so the morning cron computes exactly
 * what the Today view shows. Uses the webpack that ships with react-scripts.
 *
 *   npm run build:server   → api/_lib/daily-plan.js (committed)
 */
const path = require('path');
const webpack = require('webpack');

const root = path.resolve(__dirname, '..');

webpack({
  mode: 'none',
  target: 'node',
  entry: path.join(root, 'src/services/dailyPlan.js'),
  output: {
    path: path.join(root, 'api/_lib'),
    filename: 'daily-plan.js',
    library: { type: 'commonjs2' },
  },
  optimization: { minimize: false },
  devtool: false,
}, (err, stats) => {
  if (err || stats.hasErrors()) {
    console.error(err || stats.toString({ colors: true, all: false, errors: true }));
    process.exit(1);
  }
  const banner = '/* GENERATED by scripts/build-server.js from src/services/dailyPlan.js — do not edit. */\n';
  const fs = require('fs');
  const out = path.join(root, 'api/_lib/daily-plan.js');
  fs.writeFileSync(out, banner + fs.readFileSync(out, 'utf8'));
  console.log(`[build:server] ${path.relative(root, out)} (${Math.round(fs.statSync(out).size / 1024)} kB)`);
});
